### PR TITLE
Extending standalone with more parameters

### PR DESCRIPTION
**Pull request by MasterZydra**
This version of the `standalone.js` supports settings _hotSpotDebug, compass, autoRotateInactivityDelay, autoRotateStopDelay, authorURL, showZoomCtrl and showControls_

### CODE REVIEW

**Comment by mpetroff** [comment]
Thanks, but I am hesitant to add any additional URL parameters. You can set all of these in the standalone viewer by using a JSON configuration file.

Unless you can provide a compelling reason why these parameters should be URL parameters instead of requiring a JSON configuration file, I'm going to close this pull request.

**Comment by MasterZydra** [comment]
If there is already the interface to configure the panorama via the URL, there should also be the possibility to make settings like the display and hiding of the compass.  
For some applications, such as SharePoint SPFx webparts, implementation via standalone is easier.

**Comment by mpetroff** [comment]
There is the possibility to set these in the standalone version, via a JSON configuration file:

URL:
`pannellum.htm#config=configuration.json`

`configuration.json`:
```json
{
    "hotSpotDebug": true,
    "compass": false
}
```

**Comment by MasterZydra** [comment]
It is ok if you don't want to add the parameters. For my application case writing in a JSON file was not possible.

**Comment by mpetroff** [comment]
I'm generally not keen on adding additional parameters, so I'm going to close this.

**Pull request closed without merging**
